LinuxMediatorRelease:
  tags:
    - linux
  before_script:
    - "rm -rf ./Tools"
  stage: build
  script: 
    - "chmod ogu+x Tools/download.tools.upd.sh"
    - "./Tools/download.tools.upd.sh"
    - "chmod ogu+x 3rd/download.sh"
    - "./3rd/download.sh"
    - "chmod ogu+x Tools/build.mediator.linux.sh"
    - "./Tools/build.mediator.linux.sh"

LinuxMediatorDebug:
  tags:
    - linux
  before_script:
    - "rm -rf ./Tools"
  stage: build
  script: 
    - "chmod ogu+x Tools/download.tools.upd.sh"
    - "./Tools/download.tools.upd.sh"
    - "chmod ogu+x 3rd/download.sh"
    - "./3rd/download.sh"
    - "chmod ogu+x Tools/build.mediator.linux.sh"
    - "export DEBUG=1 && ./Tools/build.mediator.linux.sh"


OSXMakeMediatorRelease:
  tags:
    - osx
  before_script:
    - "rm -rf ./Tools"
  stage: build
  script: 
    - "chmod ogu+x Tools/download.tools.upd.sh"
    - "./Tools/download.tools.upd.sh"
    - "chmod ogu+x 3rd/download.sh"
    - "3rd/download.sh"    
    - "chmod ogu+x Tools/build.mediator.linux.sh"
    - "./Tools/build.mediator.linux.sh"

OSXMakeMediatorDebug:
  tags:
    - osx
  before_script:
    - "rm -rf ./Tools"
  stage: build
  script: 
    - "chmod ogu+x Tools/download.tools.upd.sh"
    - "./Tools/download.tools.upd.sh"
    - "chmod ogu+x 3rd/download.sh"
    - "3rd/download.sh" 
    - "chmod ogu+x Tools/build.mediator.linux.sh"
    - "export DEBUG=1 && ./Tools/build.mediator.linux.sh"


WindowsMediatorDebug:
  tags:
    - windows
  stage: build
  before_script:
    - "rm -rf ./Tools"
  script: 
    - "bash ./3rd/download.sh"
    - "bash ./Tools/download.tools.upd.sh"
    - "bash ./Tools/build.mediator.win32.sh d p"
    
WindowsMediatorRelease:
  tags:
    - windows
  before_script:
    - "rm -rf ./Tools"
  stage: build
  script: 
    - "bash ./3rd/download.sh"
    - "bash ./Tools/download.tools.upd.sh"
    - "bash ./Tools/build.mediator.win32.sh r p"

OSXMediatorRelease:
  tags:
    - osx
  before_script:
    - "rm -rf ./Tools"
  stage: build
  script:
    - "chmod ogu+x 3rd/download.sh"
    - "./3rd/download.sh"
    - "chmod ogu+x Tools/download.tools.upd.sh"
    - "./Tools/download.tools.upd.sh"
    - "chmod ogu+x Tools/build.mediator.osx.sh"
    - "./Tools/build.mediator.osx.sh unattended"

OSXMediatorDebug:
  tags:
    - osx
  before_script:
    - "rm -rf ./Tools"
  stage: build
  script:
    - "chmod ogu+x 3rd/download.sh"
    - "./3rd/download.sh"
    - "chmod ogu+x Tools/download.tools.upd.sh"
    - "./Tools/download.tools.upd.sh"
    - "chmod ogu+x Tools/build.mediator.osx.sh"
    - "./Tools/build.mediator.osx.sh unattended d"
    
            